### ISSUE TITLE
Incorrect result

### ISSUE THREAD

**Issue by zulqasar** [atlopes/iCal4VFP#1]
local oCal, lcRule, ldBeg, ldEnd

do locfile('iCalLoader.prg')
oCal = createobject('iCalPropRRule')

lcRule = "rrule:freq=yearly;wkst=MO;interval=1;bymonth=1;bymonthday=1;count=10"
ldBeg = date()
ldEnd = gomonth(m.ldBeg, 720)

oCal.Parse(m.lcRule)
lcAlias = oCal.CalculateAll(ldBeg, dtot(ldEnd))
select (m.lcalias)
scan
  if ttod(local time) = m.ldBeg
      loop
   endif
  ? ttod(localtime)
endscan

*--- and this is what I get.  The 14th day gets added no matter what bymonth or bymonthday I add
01/01/2023
01/14/2023
01/01/2024
01/14/2024
...

*-- Another problem is with this rule
lcRule = "rrule:freq=monthly;wkst=MO;interval=1;bymonth=3,6,9,12;bymonthday=2;count=10"
 If bymonthday is anything other than 1, the 1st of month date is also added to the result set.

**Comment by zulqasar** [comment]
The solution I found:

the 14th day of the month being returned is the day in ldBeg.

If we comment out lines 782, 783 and 784 in iCalProperties.prg in function ApplyByMonth we get correct results for problem # 1

```VFP
Hidden function ApplyByMonth (...)
    *-- lines 782, 783, 784
    if m.Dates.GetKey(TTOC(m.CalcDate, 1)) = 0
        m.Dates.Add(m.CalcDate, TTOC(m.CalcDate, 1))
    endif 
```

**Comment by zulqasar** [comment]
Solution to problem # 2 where the 1st of month date is added to the result set

Comment out lines 793, 794, and 795 in the same function stated above for problem # 1

**Comment by zulqasar** [comment]
Excellent job Antonio. I program in VFP and Python and l have a project in Python which has a scheduler build upon RRule in dateUtil library by Paul Gansole. I was not expecting that RRule or iCalendar libraries here in VFP. 

Again hats off to you.

**Comment by atlopes** [comment]
Thank you, Zulqasar.

According to RRULE specifications, in https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html,

> "The ["DTSTART"](https://icalendar.org/iCalendar-RFC-5545/3-8-2-4-date-time-start.html) property value SHOULD be synchronized with the recurrence rule, if specified. The recurrence set generated with a ["DTSTART"](https://icalendar.org/iCalendar-RFC-5545/3-8-2-4-date-time-start.html) property value not synchronized with the recurrence rule is undefined."

So, instead of
`ldBeg = date()`

it should (could) be something like this
`ldBeg = {^2023-01-01}`

But I'll look into your suggestions and evaluate their impact.

Thank you, once again!

**Comment by zulqasar** [comment]
Yes the DTSTART property value should be synchronized and it gets synchronized. The problem is with the other dates in subsequent years with the same month and day values from DTSTART.

Thanks again.

**Comment by atlopes** [comment]
The DTSTART property must be given to the Recurrence Rule engine; it is not calculated. When you call the CalculateAll method, the first argument is the start date, the equivalent of DTSTART. As stated above, _it should be synchronized with the recurrence rule_.

That is,

```
DTSTART:20220101
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=1;BYMONTHDAY=1;COUNT=10
```

or

`m.oCal.CalculateAll({^2022-01-01}, {^9999-12-31})`

are ok, because 2022-01-01 is synchronized with the rule that creates a set of ten January 1st dates.

But

```
DTSTART:20221214
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=1;BYMONTHDAY=1;COUNT=10
```

or

`m.oCal.CalculateAll({^2022-12-14}, {^9999-12-31})`

are not ok because 2022-12-14 is not synchronized with the same rule. Therefore, it shouldn't be used as a start date for the rule, either as a DTSTART property or as the Start parameter of a Calculate method call. Otherwise, the result set would be _undefined_.

I hope I managed to explain it more clearly, this time.

**Comment by atlopes** [comment]
As for the second problem, with the result set produced by the rule:

`RRULE:FREQ=MONTHLY;WKST=MO;INTERVAL=1;BYMONTH=3,6,9,12;BYMONTHDAY=2;COUNT=10`

I confirm that the set of dates is incorrect. I'm looking into it and will come back with (hopefully) a solution.

Thank you for pointing that out.

**Comment by atlopes** [comment]
The last commit seems to address the problem by ensuring a legal date only if needed after adding an interval in yearly and monthly frequencies instead of preemptively starting with a safe date.

Your confirmation would be greatly appreciated.

**Comment by zulqasar** [comment]
I think there is a misunderstanding about DTSTART. It is simply the starting point from where the events should be generated. If not specified the current date should be assumed. I have confirmed it with both Python and JS. 

Here is a online demo for js https://jakubroztocil.github.io/rrule/

After the latest update the problem remains unsolved and here is the result set:

DTSTART for all tests is 12/21/2022. It gets included with all result sets and is not a problem. May be its part of the RFC rule and can easily be filtered out. 

TEST 1: Every month on the 6th (result: correct)
RRULE:FREQ=MONTHLY;WKST=MO;INTERVAL=1;BYMONTHDAY=6:COUNT=4
   12/21/2022, 1/6/2023, 2/6/2023, 3/6/2023, 4/6/2023

TEST 2: Every quarter on the 6th (Result: incorrect because the BYMONTHDAY part of RRULE does NOT contain the day  21 but gets included in the events generated)
RRULE:FREQ=MONTHLY;WKST=MO;INTERVAL=1;BYMONTH=3,6,9,12;BYMONTHDAY=6:COUNT=10
12/21/2022, 3/6/2023, **3/21/2023**, 6/6/2023, **6/21/2023**, 9/6/2023, **9/21/2023**, 12/6/2023, **12/21/2023**

TEST 3: Every year in January on the 6th (Result: incorrect because the BYMONTHDAY part of RRULE does NOT contain the day 21 but gets included in the events generated)
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=1;;BYMONTHDAY=6:COUNT=10
12/21/2022, 1/6/2023, **1/21/2023**, 1/6/2024, **1/21/2024**...

The problem occurs only when both BYMONTH and BYMONTHDAY are specified.

**Comment by zulqasar** [comment]
Found couple of errors after the update in iCalProperties.prg Calculate method on line 673 and 678 

TTOD(m.Current) ---> m.Current is of type date and not DateTime

Case m.Rule.Freq == "WEEKLY"
*-- line 673
    m.DatePart = **_TTOD(m.Current)_** + DAYS_OF_WEEK + m.Interval
    ...

Case m.Rule.Freq == "DAILY"
*-- line 678
    m.DatePart = **_TTOD(m.Current)_** + m.Interval

**Comment by atlopes** [comment]
Zulqasar, once again, thank you for your interest and remarks.

Based on your suggestion, I moved all date insertions in the recurrence set to a single place after all by-part rules were successfully processed (while limiting or expanding dates).

As a consequence, a null or empty DTSTART is now possible.
